org: mattberserk

service: productService

provider:
  name: aws
  runtime: nodejs22.x
  environment:
    BUCKET_NAME: product-images-matt-lino-12340
    DYNAMO_TABLE: Products

  httpApi:
    authorizers:
      myCognitoAuth: #Custom name for Cognito Authorization(used in routes)
        identitySource: $request.header.Authorization #Extract JWT token from Authorization
        #header (used for validation)
        issuerUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_y0NwyvEfn/
        #Url of your Cognito user pool(Needed to  verify tokens).
        audience:
          - 51s363ja1rdpaop0vtp1tgn202
          #Cognito App client ID(ensures tokens come from the right app).

resources:
  Resources:
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    ProductImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: product-images-matt-lino-12340
    ProductCleanupTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ProductCleanupTopic
    CategoryCleanupSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: arn:aws:sns:us-east-1:958313499473:ProductCleanupTopic
        Protocol: email
        Endpoint: matheuslino86a@gmail.com
functions:
  getUploadUrl:
    handler: handlers/getUploadUrl.getUploadUrl
    events:
      - httpApi:
          path: /get-upload-url
          method: post
          authorizer:
            name: myCognitoAuth
  getApprovedProducts:
    handler: handlers/getApprovedProducts.getApprovedProducts
    events:
      - httpApi:
          path: /approve-products
          method: get

  updateProductImage:
    handler: handlers/updateProductImage.updateProductImage
    events:
      - s3:
          bucket: product-images-matt-lino-12340
          event: s3:ObjectCreated:Put #Trigger event when a new object is uplaod
          existing: true #ensures the function works with  an existing bucket
  cleanupProducts:
    handler: handlers/cleanupProducts.cleanupProducts
    events:
      - schedule: rate(2 minutes) #Runs every 2 minutes
