org: mattberserk
service: orderService

provider:
  name: aws
  runtime: nodejs22.x
  environment:
    DYNAMO_TABLE: Orders
    SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/958313499473/OrderQueue
  httpApi:
    authorizers:
      myCognitoAuth:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_y0NwyvEfn
        audience:
          - 51s363ja1rdpaop0vtp1tgn202
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
      Resource:
        - arn:aws:sqs:us-east-1:958313499473:OrderQueue
        - arn:aws:dynamodb:us-east-1:958313499473:table/Orders
resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Orders
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    OrderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: OrderQueue
functions:
  placeOrder:
    handler: handlers/placeOrder.placeOrder
    events:
      - httpApi:
          path: /
          method: post
          authorizer:
            name: myCognitoAuth
  processOrder:
    handler: handlers/processOrder.processOrder
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:958313499473:OrderQueue
